export const countryList = [
  { code: "US", name: "United States" },
  { code: "CN", name: "China" },
  { code: "IN", name: "India" },
  { code: "JP", name: "Japan" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "GB", name: "United Kingdom" },
  { code: "BR", name: "Brazil" },
  { code: "RU", name: "Russia" },
  { code: "CA", name: "Canada" },
  { code: "IT", name: "Italy" },
  { code: "AU", name: "Australia" },
  { code: "KR", name: "South Korea" },
  { code: "MX", name: "Mexico" },
  { code: "ZA", name: "South Africa" },
  { code: "ES", name: "Spain" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "TR", name: "Turkey" },
  { code: "ID", name: "Indonesia" },
  { code: "AR", name: "Argentina" },
  { code: "EG", name: "Egypt" },
  { code: "TH", name: "Thailand" },
  { code: "NG", name: "Nigeria" },
  { code: "PK", name: "Pakistan" },
];

export const languageList = [
  { code: "en", language: "English" },
  { code: "zh", language: "Mandarin Chinese" },
  { code: "hi", language: "Hindi" },
  { code: "es", language: "Spanish" },
  { code: "fr", language: "French" },
  { code: "ar", language: "Arabic" },
  { code: "bn", language: "Bengali" },
  { code: "pt", language: "Portuguese" },
  { code: "ru", language: "Russian" },
  { code: "ur", language: "Urdu" },
  { code: "id", language: "Indonesian" },
  { code: "de", language: "German" },
  { code: "ja", language: "Japanese" },
  { code: "sw", language: "Swahili" },
  { code: "pa", language: "Punjabi" },
  { code: "jv", language: "Javanese" },
  { code: "te", language: "Telugu" },
  { code: "vi", language: "Vietnamese" },
  { code: "ko", language: "Korean" },
  { code: "mr", language: "Marathi" },
  { code: "ta", language: "Tamil" },
  { code: "tr", language: "Turkish" },
  { code: "fa", language: "Persian (Farsi)" },
  { code: "it", language: "Italian" },
  { code: "pl", language: "Polish" },
];

export const tags = [
  { label: "Vlogs", value: "vlogs" },
  { label: "Gaming", value: "gaming" },
  { label: "Education", value: "education" },
  { label: "Tech Reviews", value: "tech_reviews" },
  { label: "Tutorials", value: "tutorials" },
  { label: "Beauty & Fashion", value: "beauty_fashion" },
  { label: "Fitness", value: "fitness" },
  { label: "Food & Cooking", value: "food_cooking" },
  { label: "Music", value: "music" },
  { label: "Comedy", value: "comedy" },
  { label: "News & Politics", value: "news_politics" },
  { label: "Finance", value: "finance" },
  { label: "Travel", value: "travel" },
  { label: "Animation", value: "animation" },
  { label: "Science & Experiments", value: "science_experiments" },
  { label: "Short Films", value: "short_films" },
  { label: "Motivation", value: "motivation" },
  { label: "Automobiles", value: "automobiles" },
  { label: "DIY & Crafts", value: "diy_crafts" },
  { label: "Unboxing & Reviews", value: "unboxing_reviews" },
  { label: "Podcasts", value: "podcasts" },
  { label: "Spirituality", value: "spirituality" },
  { label: "Memes & Trends", value: "memes_trends" },
  { label: "Photography", value: "photography" },
  { label: "Art & Drawing", value: "art_drawing" },
];

export const privacy = ["public", "private"];
